### ISSUE TITLE
Kết nối  bị lỗi

### ISSUE THREAD

**Issue by ghost** [Vietworm/Crab.JS#1]
Lần đầu mình kết nối thì ok,
![image](https://cloud.githubusercontent.com/assets/19475218/20434431/56044630-adda-11e6-9454-4abd0f7b443e.png)
 và mình chạy https://localhost:3000/admin/ thì lỗi như thế này
![image](https://cloud.githubusercontent.com/assets/19475218/20434475/7fcc4058-adda-11e6-828b-84552ad006ca.png)
Mình chạy http://localhost:3000/ thì có lỗi như sau
![image](https://cloud.githubusercontent.com/assets/19475218/20434651/5da61f2a-addb-11e6-9737-dbe64a0062ec.png)
và node server.js xuất hiện lỗi sau
![image](https://cloud.githubusercontent.com/assets/19475218/20434772/0373e6c6-addc-11e6-99dd-c34c8c0e1a4f.png)

Và đây là thông số mình databatabse và cấu hình lại tên database trong file env-development.js và env-production.js
![image](https://cloud.githubusercontent.com/assets/19475218/20434698/b19d2f6a-addb-11e6-8717-bae18f4ab1ba.png)
![image](https://cloud.githubusercontent.com/assets/19475218/20434710/c2c2c052-addb-11e6-88a3-4f35621c71b1.png)
![image](https://cloud.githubusercontent.com/assets/19475218/20434722/ce08498c-addb-11e6-84dc-99c57c5fd8e8.png)
host: 'localhost:27017',//127.0.0.1:27017 mình có thay đổi qua lại vẫn bị lỗi.
 Mình mới tìm hiểu nên còn gà lắm, mong bạn chỉ giáo. Cảm ơn bạn nhiều.

**Comment by lephuhai** [comment]
Lỗi này là do bạn chưa bật `redis`. 

Sử dụng redis để lưu session đăng nhập của người dùng và flash message.

Bạn có thể cài đặt redis trên windows theo hướng dẫn sau: [https://github.com/ServiceStack/redis-windows#current-version-30503-june-28-2016](https://github.com/ServiceStack/redis-windows#current-version-30503-june-28-2016)

Command: `redis-server`

**Comment by lephuhai** [comment]
Mình đã xử lý lỗi này và đưa ra thông báo lỗi cho bạn biết nếu bạn chưa chạy `redis`. Bạn có thể pull code mình mới cập nhật về bằng câu lệnh: `git pull`

**Comment by ghost** [comment]
Cảm ơn bạn nhiều nhé.
